---

- name: Install nginx and php5-fpm
  apt: name={{item}} state=installed
  with_items:
  - nginx
  - php5-fpm
  - php-apc
  notify:
  - reload nginx
  - restart php5-fpm

- name: set php tunables
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp="^;?{{item.key}}"
              line="{{item.key}} = {{item.value}}"
              backup=yes
  with_dict: "{{tunables|default({})}}"
  notify: restart mysql

- name: Install php5 packages
  apt: name={{item}} state=installed
  with_items: "{{php5_packages|default([])}}"
  notify:
  - restart php5-fpm

- name: enable nginx and php5-fpm
  service: name={{item}} enabled=yes state=started
  with_items:
  - nginx
  - php5-fpm

# On Ubuntus this is usually a TCP port. We'd rather use a unix socket...
- name: set php5-fpm socket location
  lineinfile:
    dest: /etc/php5/fpm/pool.d/www.conf
    regexp: '^listen ?='
    line: 'listen = /var/run/php5-fpm.sock'
  notify:
  - restart php5-fpm

- name: set ownership and permissions of php5-fpm socket
  file:
    path: /var/run/php5-fpm.sock
    owner: root
    group: www-data
    mode: 660
